version: '3.8'
services:
  petclinic:
    image: petclinic_back-end_dev:latest
    container_name: petclinic_back-end_dev
    build:
      context: .
      target: development
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/petclinic
    volumes:
      - ./:/app
    depends_on:
      - mysqlserver

  mysqlserver:
    image: mysql:latest
    container_name: petclinic_mysql_dev
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - mysql_data_dev:/var/lib/mysql
      - mysql_config_dev:/etc/mysql/conf.d

volumes:
  mysql_data_dev:
  mysql_config_dev:

networks:
  default:
    # Use a custom driver
    name: "petclinic_network_dev"
 