name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: petclinic-label
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t petclinic_back-end_dev  --target development .

