name: build

on:
  push:
    branches:
      - main

jobs:
  build_qa:
    runs-on: petclinic-label
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Commit
        run: echo Start Build QA Docker Image ${{ github.sha }}
      - name: Build Docker Image
        run: docker build -t petclinic_back-end_dev/${{ github.sha }}:latest  --target development .
  deploy_qa:
    needs: build_qa
    runs-on: petclinic-label
    steps:
      - name: Start Deploy QA
        run: docker service update --force --image petclinic_back-end_dev/${{ github.sha }}:latest petclinic_qa_petclinic
      - name: Remove unused images
        run: docker image prune -a -f
   
