name: test

on:
 push:
   branches:
     - huynhnhathn-patch-1
jobs:
   job1:
    runs-on: ubuntu-latest
    steps:
      - run: |
             GIT_PR_SHA="${{ github.sha }}"
             echo "::debug::Traning condination"
