name: test

on:
 push:
   branches:
     - huynhnhathn-patch-1
jobs:
   job1:
    runs-on: ubuntu-latest
    steps:
       - name: Set color
         id: color-selector
         run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"
         
       - name: Get color
         id: step_two
         env:
          SELECTED_COLOR: ${{ steps.color-selector.outputs.SELECTED_COLOR }}
         run: echo "The selected color is $SELECTED_COLOR"
        
